# Generated by Django 3.2.5 on 2023-11-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='default value'),
            preserve_default=False,
        ),
    ]
